version: '3.8'

services:
  jupyterlab:
    build: .
    ports:
      - "8888:8888" # JupyterLab
      - "6006:6006" # Arize Phoenix
    volumes:
      - .:/usr/src/app
    environment:
      - JUPYTER_ENABLE_LAB=yes